### ISSUE TITLE
jquery not loading, not defined

### ISSUE THREAD

**Issue by jaredarkin** [ga-dc/pbj-project3#12]
We have the ajax script linked in the layout.hbs. We are trying to run a function with an ajax request in one of our modules. Our module is exported correctly - we can run a simple console.log function from it.

We get a reference error: $ is not defined when we try to load the view that runs the function. We have tried the $(document).ready around all of our code in the script file. However, we get the same reference error whether we have it or not.

Our scripts:

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="/public/js/marketAPI.js"></script>
<script src="/public/js/script.js"></script>
```

**Comment by RobertAKARobin** [comment]
Have you included jQuery in there?

**Comment by jaredarkin** [comment]
yeah it's not showing up. it's supposed to be the first script. when we posted the issue, that script line doesn't show in the message

**Comment by RobertAKARobin** [comment]
Hmmm. So you're writing `<script src="jquery.js"></script>` or similar in your HBS, but it's not showing up?

**Comment by jaredarkin** [comment]
<img width="655" alt="screen shot 2015-08-24 at 2 55 25 pm" src="https://cloud.githubusercontent.com/assets/12718947/9449381/382482c0-4a70-11e5-86fb-fd8ed79d3a47.png">

**Comment by RobertAKARobin** [comment]
Oh, hah. Fixed it. Make sure to put the three backtics above and below anything you want to display as code. Otherwise, my browser thinks you want me to actually render the HTML you wrote!

See this:

<h1>Hello</h1>

...versus this:

```
<h1>Hello</h1>
```

**Comment by jaredarkin** [comment]
ok, got the scripts to show up in the original issue.

**Comment by RobertAKARobin** [comment]
If it doesn't seem to be loading jQuery from GoogleAPIs, try download jQuery and saving it locally on your computer. That'll also speed things up a tiny bit. It's what I usually do so I can use jQuery without an internet connection.

Can you show the script containing the `$(document).ready()` ? Can you show the specific line that's causing the error?

**Comment by jaredarkin** [comment]
omari is working on saving it locally - still getting the same error.

"referenceerror $ is not defined" error occurred when ever the code got to a $.
we had $(document).ready(function(){} around all of the following code, but we got the same error.
The sayHello function works.

```
// Farmers Market API

module.exports = {
   sayHello: function() {
       console.log("Hello! Market API")
   },

   marketResults: function(zip) {
       // or
       // function getResults(lat, lng) {
       $.ajax({
           type: "GET",
           contentType: "application/json; charset=utf-8",
           // submit a get request to the restful service zipSearch or locSearch.
           url: "http://search.ams.usda.gov/farmersmarkets/v1/data.svc/zipSearch?zip=" + zip,
           // or
           // url: "http://search.ams.usda.gov/farmersmarkets/v1/data.svc/locSearch?lat=" + lat + "&lng=" + lng,
           dataType: 'jsonp',
           jsonpCallback: 'searchResultsHandler'
       });
   },

   //iterate through the JSON result object.
   searchResultsHandler: function(searchResults) {
       for (var key in searchresults) {
           alert(key);
           var results = searchresults[key];
           for (var i = 0; i < results.length; i++) {
               var result = results[i];
               for (var key in result) {
                   //only do an alert on the first search result
                   if (i == 0) {
                       alert(result[key]);
                   }
               }
           }
       }
   }
}
```

**Comment by RobertAKARobin** [comment]
Let's worry about the rest of your Javascript later. For now, let's just see if we can get jQuery to work and go from there.

Try commenting out all the `<script>` tags except the one for jQuery. Then, add something like this directly in your HTML:

```
<script>
$(document).ready(function(){
  alert("Hello, jQuery is working!");
});
</script>
```

**Comment by jshawl** [comment]
Module.exports is only used for requiring files in node try removing that and using a global variable instead?

**Comment by RobertAKARobin** [comment]
You can't natively use jQuery with Node. So if you're trying to do something like `$` in your _Node_ Javascript, it won't work. That's back-end Javascript. jQuery only works with front-end Javascript: that is, everything in `<script>` tags.

Similarly, `module.exports` is exclusively a back-end thing. You can't use `module.exports` in the front-end.

Sorry, should have seen that, but I'm so used to seeing `module.exports` everywhere that it slipped past!

**Comment by jaredarkin** [comment]
ahhh, okay. we figured it out - put all the api js in the hbs file in our view. thanks!

**Comment by jshawl** [comment]
:+1:
