### ISSUE TITLE
error with running db/migrate.js

### ISSUE THREAD

**Issue by LauraWN** [ga-dc/pbj-project3#13]
When running $node db/migrate.js, we get the following error: The dialect postgress is not supported. cannot find module ./dialects/postgress'.

We have the module pg-hstore installed, which was a recommended google solution. we also have sequelize installed.

**Comment by RobertAKARobin** [comment]
You have a few too many `s` in `postgress`!

**Comment by LauraWN** [comment]
hahahahaha.

**Comment by LauraWN** [comment]
yeah, so you can close this now.

**Comment by RobertAKARobin** [comment]
Or you can! You should be able to click "Close Issue" or something below.

**Comment by RobertAKARobin** [comment]
:+1:
