### ISSUE TITLE
Sequelize Assocations Question

### ISSUE THREAD

**Issue by nolds9** [ga-dc/pbj-project3#14]
Is there any kind of equivalent in Sequelize to Active Record's 
`dependent: :destroy`
that we could attach to our associations. So we could delete all comments attached to a post when a post is deleted for example...

we looked around and tried: 

```
Post.hasMany(Comment, {onDelete: 'CASCADE'});
```

but when we delete a post, the comments attached to that post are not deleted as well.

**Comment by RobertAKARobin** [comment]
Did you re-run your migration after adding that? Any chance you could push your code to Github and link to it here?

**Comment by RobertAKARobin** [comment]
Hold that thought. Try putting it in the `belongsTo`:

```
Task.belongsTo(List, {onDelete: "cascade"});
List.hasMany(Task);
```

**Comment by nolds9** [comment]
Worked! Thanks, makes more sense looking at, just was used to how Active Record handles it.

**Comment by RobertAKARobin** [comment]
Wooo! No worries.
