### ISSUE TITLE
Not finding script.js from index.html

### ISSUE THREAD

**Issue by tomBeach** [ga-dc/pbj-project3#15]
Our client side js script is in "public/js/" directory structure.  Index.html file script tag is:

`<script type="text/javascript" src="/public/js/script.js"></script>`

The index file can't find the script.js file.  Does the issue have something to do with this line in our app.js file?

`app.use("/public", express.static(path.join(__dirname + "/public")));`

Thank you!

**Comment by tomBeach** [comment]
We got it!

**Comment by RobertAKARobin** [comment]
Darn, you beat me. What was the trouble?
