### ISSUE TITLE
Spotify API/embedded player issues

### ISSUE THREAD

**Issue by msteffan** [ga-dc/pbj-project3#16]
We are using the Echonest API to embed tracks on our page in a Spotify player. The embed works, but to play the track, Spotify opens a new window and plays it from the Spotify web app instead of from our page. So we are wondering if there's a way to force the embedded player not to open a new tab, but to play it in-app.

Additionally, it throws an error for every item in the playlist:
![screen shot 2015-08-24 at 4 55 53 pm](https://cloud.githubusercontent.com/assets/7719096/9452213/0c26ec56-4a81-11e5-8159-97348a306ff7.png)

We have worked through the first couple pages of StackOverflow search results for this type of error, and we've being trying to debug it all afternoon. This is the  only post that offered any insight...but not encouraging insight: http://stackoverflow.com/questions/22509778/spotify-play-button-spotilocal-com-error-err-connection-refused
@jshawl Andy mentioned that you might be familiar with a way to get around either/both of these—any ideas?

**Comment by jshawl** [comment]
oh wow. I personally have struggled so much with this sort of thing. I think Spotify in particular is going to be difficult to circumnavigate - as their platform is almost entirely web-based. i.e. they want even developers to play songs through their app. 

I'm not sure what spotilocal is (in the url) other than maybe it's trying to connect to the SPotify app to know if you're currently listening or not?

**Comment by jshawl** [comment]
is it an error other than logging an error in the console?

**Comment by RobertAKARobin** [comment]
I'm going to close this since it hasn't had updates in a while. Please create a new issue linking to this one if need-be!

**Comment by good-idea** [comment]
I was having this issue and tried opening up my page in a private window, with extensions disabled - and it worked. Looks like an ad blocker is preventing connection, at least in my case.
