### ISSUE TITLE
Connect Sequelize to my database

### ISSUE THREAD

**Issue by Curtismn87** [ga-dc/pbj-project3#17]
We're following Robin's list of setting up sequelize and we are having troubles with the Connect Sequelize to my database portion. We have our models/and connect.js files but our database says there are no tables. What do we do next?

**Comment by RobertAKARobin** [comment]
Have you run a migration/sync yet?

**Comment by Curtismn87** [comment]
we ran node db/connection.js which is where the file is. It was giving us errors before but now we... think it works??

**Comment by RobertAKARobin** [comment]
That may not be the migration file... The migration file is wherever you put `sync({force: true})`

**Comment by Curtismn87** [comment]
Ok, so we made a migration.js file in our db directory. We copied the schema.js from the Tunr in class example because there was no migration.js file in tunr and schema.ja has sync({force: true}) included in it. Now it's telling me that sync is not a function

**Comment by RobertAKARobin** [comment]
Did you require Sequelize, or require your connection file which contains Sequelize? See here: https://github.com/ga-dc/do_something_express_part4/blob/solution/config/migrate.js

**Comment by RobertAKARobin** [comment]
For a better indication of which names map to what, you might look here too: https://github.com/ga-dc/my_dank_app/blob/multifile1/run_me_to_migrate.js

**Comment by Curtismn87** [comment]
Still telling us "Cannot read property 'sync' of undefined"

**Comment by RobertAKARobin** [comment]
Can you show me the contents of your migration file, and the contents of your connection file?

**Comment by Curtismn87** [comment]
migrate.js : var DB = require("./connection");

DB.sequelize.sync({force: true}).then(function(){
  process.exit();
});

connection.js:

// ======= ======= ======= DB connection.js ======= ======= =======
var Sequelize = require("sequelize");
var sequelize = new Sequelize("postgres:///mystox_db");
var User = sequelize.import("../app/models/user");

module.exports = {
  sql: Sequelize,
  dbobj: sequelize,
  models: {
    User: User,
  }
};

**Comment by RobertAKARobin** [comment]
DB in your migration file is the object you made at the end of your connection file. Calling "DB.sequelize" means you want the object's "sequelize" propert, but that doesn't exist. You gave it three properties: "sql", "dbobj", and "models". One of those three properties is the one you want.

**Comment by RobertAKARobin** [comment]
Sorry, Im typing poorly from my phone.

**Comment by Curtismn87** [comment]
AHHH... 
DB.dbobj.sync({force: true}).then(function(){
  process.exit();
});

I get it now, I thought the .sequelize was convention for sequelize. I didn't realize you just called the sequelize object in the tunr migrate file sequelize...

**Comment by RobertAKARobin** [comment]
Yup!
