### ISSUE TITLE
Simple (?) html tables issue?

### ISSUE THREAD

**Issue by tomBeach** [ga-dc/pbj-project3#20]
I am creating a table string with the code below.  The header row formats correctly, and the data row prints stockJson.Name correctly (row2, if header row = row1), but the remaining data prints on a third row (to far left under stockJson.Name data).  I tried removing the <h3> tags but no difference.  I had previously tried building up the header string through concatenation (as data row currently is) and spliced it into a single string as one thing to try fixing problem but again no diff...

``` js
        var container = $(".contents");
        container.empty();
        container.css("margin-top", 0);
        this.$el = $("<div class='stock'></div>");
        var htmlString = $("<table><tr><th>Name</th><th>Symbol</th><th>Low</th><th>High</th><th>LastPrice</th></tr>");
        htmlString.append("<tr><td><h3>" + stockJson.Name + "</h3></td>");
        htmlString.append("<td>" + stockJson.Symbol + "</td>");
        htmlString.append("<td>" + stockJson.Low + "</td>");
        htmlString.append("<td>" + stockJson.High + "</td>");
        htmlString.append("<td>" + stockJson.LastPrice + "</td>");
        htmlString.append("</tr></table>");
        this.$el.html(htmlString);
        $(".contents").append(this.$el);
```

Here's css styling for table but wouldn't think this would cause trouble..

``` css
table, th, td {
    border: 1px solid red;
    border-collapse: collapse;
}
th, td {
    padding: 10px;
}
```

Any thoughts?  Thanks!

**Comment by RobertAKARobin** [comment]
Can you show me a screenshot, Tom?

Better yet, can you also show me the HTML as it's rendered? To do this, "inspect element" on the element in question. Then, with it highlighted in the inspector, press the "fn" key and the "F2" key (it's also the "increase brightness" on my laptop, may be different on yours). That should open the HTML in an editable text box, as I've shown in the screenshot attached.

![screen shot 2015-08-25 at 9 26 02 am](https://cloud.githubusercontent.com/assets/6268177/9467677/5d4a3586-4b0b-11e5-91fb-2cba2a3cfbf1.png)

**Comment by tomBeach** [comment]
Thanks Robin -- couldn't get more than one element with the editable text option (good to know about though!) so I tried a screen shot.  Looks like an extra </tr> is there as well as a </tbody> tag.  Where'd those come from???

<img width="407" alt="screen shot 2015-08-25 at 9 34 51 am" src="https://cloud.githubusercontent.com/assets/10157094/9467899/aeb8f1fe-4b0c-11e5-99d0-9b0d8534eba6.png">

**Comment by RobertAKARobin** [comment]
I think the trouble here is `.append`. It's treating `htmlString` as a _complete element_. So when the browser sees `htmlString.append("whatever")`, it thinks "OK, I should append 'whatever' to the end of this htmlString element. Hmm... htmlString appears to be a table, but it doesn't have a closing `</table>` tag. 'Appending' means I should put 'whatever' _after_ a closing `</table>` tag, but since this element doesn't have one, I'm not sure what to do!"

So try making htmlString into a jQuery object **after** you've completed the string:

``` js
var htmlString = "<table><tr><th>Name</th><th>Symbol</th><th>Low</th><th>High</th><th>LastPrice</th></tr>" +
  "<tr><td><h3>" + stockJson.Name + "</h3></td>" +
  "<td>" + stockJson.Symbol + "</td>" +
  "<td>" + stockJson.Low + "</td>" +
  "<td>" + stockJson.High + "</td>" +
  "<td>" + stockJson.LastPrice + "</td>" +
  "</tr></table>";
this.$el.html(htmlString);
```

**Comment by tomBeach** [comment]
Got it!  Thanks!!!
