### ISSUE TITLE
Bootstrap Layout

### ISSUE THREAD

**Issue by kristingreenslit** [ga-dc/pbj-project3#21]
We've determined that we need to create a layout before moving forward with more functionality. We've installed bootstrap and have a layout design on a white board, but would like the help of a "css specialist." 

We're in classroom 1.

**Comment by RobertAKARobin** [comment]
I'm happy to come over, but I'd encourage your group to have one person dedicate themselves to the CSS while the rest of you work on other things. CSS is a _huge_ time-suck, and it's very easy to spend literally weeks moving a div 5 pixels left and right trying to figure out which way you like better. Also, it doesn't have any effect on your app's functionality: an app without CSS works exactly the same as an app with CSS, it just doesn't look the same. (Refer back to http://www.bettermotherfuckingwebsite.com for inspiration!)

If you still _really really_ want someone to come over, let me know and I'll come help out. But I'd encourage you to leave the CSS alone, or if it's really driving you bananas, start by just changing the font you're using and maybe giving your app some nice, soft background colors. That's an easy win, compared to positioning and layout which takes a very long time.

**Comment by RobertAKARobin** [comment]
Also, Bootstrap is a lot like Devise: it's a huge control freak, and that can majorly slow down your development. I'd suggest uninstalling it, and treating Bootstrap as a "nice-to-have" that you put in at the end if you have time.

**Comment by kristingreenslit** [comment]
Thanks Robin. We'll icebox this until Thursday.

**Comment by RobertAKARobin** [comment]
Yesssssssss.
