### ISSUE TITLE
Access control header problem with ajax request

### ISSUE THREAD

**Issue by tomBeach** [ga-dc/pbj-project3#23]
We're getting this error from our ajax re quest:

```
No 'Access-Control-Allow-Origin' header is present on the requested resource
```

Couldn't find a fix in spite of numerous explanations via google.  The puzzling thing is that the the response seems to return the json data we want.  (Clicking on the error in the console opens a page with the proper response.)  Here is the url variable and the calling function:

```
this.dataSource = "http://marketdata.websol.barchart.com/getHistory.json?key=5c566d2e239b7f0d6f2c73f38a767326&symbol=" + historySymbol + "&type=daily&startDate=20140822000000";

      HistoryData.prototype.getHistory = function() {
        console.log("getHistory");
        if (this.ajaxRequest) { this.ajaxRequest.abort(); }
        this.ajaxRequest = $.ajax({
            data: { symbol: historySymbol },
            type: 'GET',
            dataType: "json",
            // dataType: 'jsonp',
            crossDomain: true,
            url: this.dataSource,
            success: this.handleSuccess,
            error: this.handleError,
            context: this
        });
      };
```

**Comment by RobertAKARobin** [comment]
Urgh, these are annoying. Can you put `jsonp` back in there as the `dataType` and let me know if the error has changed?

**Comment by tomBeach** [comment]
We tried that (and also changed the url from json to jsonp) but got no response (neither success or failure).  I read something about making our server into a proxy server but that sounds like overkill...

**Comment by RobertAKARobin** [comment]
Can you leave it with `jsonp`, and instead of `.done` or `.fail` try `.always` and see what that gives you, like so:

``` js
$.ajax({
// blah blah blah
}).always(function(response){
  console.log("If you're seeing this it means this is running.");
  console.log(response);
});
```

**Comment by RobertAKARobin** [comment]
Incidentally, what's with this stuff?

``` js
if (this.ajaxRequest) { this.ajaxRequest.abort(); }
this.ajaxRequest = $.ajax({})
```

...that is, checking for an AjaxRequest and saving your request to a variable? That looks complicated!

**Comment by tomBeach** [comment]
^^^ above code not ours ^^^
We added the always option and changed to jsonp but still no response.  Then tried both json and jsonp in both url and datatype settings.  When both were identical (url and datatype) we got this error:

```
Uncaught SyntaxError: Unexpected token :
```

Within the error message we get a clickable link that opens the json data object that we want.

**Comment by RobertAKARobin** [comment]
Can you give me an example of what `historySymbol` is? I'll try this on my own machine.

Edit: Never mind, looks like a stock symbol.

**Comment by tomBeach** [comment]
It's a stock ticker, like "AAPL" or "GOOGL"

**Comment by RobertAKARobin** [comment]
Sorry, Tom, still working on this.

**Comment by RobertAKARobin** [comment]
The simplest solution is to not use AJAX to make cross-domain requests. Instead, use server-side HTTP. Check this out:

http://stackoverflow.com/questions/8515872/simple-api-calls-with-node-js-and-express

The reason this is such a pain is that AJAX requests are considered "less trustworthy" than server-side requests, hence all the "cross domain not allowed blah blah" stuff. AJAX is perfectly fine for making requests to your own server, but it's tricky to other servers.

**Comment by RobertAKARobin** [comment]
There hasn't been an update in a while, so I'm going to close this. Feel free to create a new issue linking to this one!
