### ISSUE TITLE
Adding users to db with/after oauth

### ISSUE THREAD

**Issue by msteffan** [ga-dc/pbj-project3#25]
I am trying to save users' spotify user IDs to our database after they authenticate with Spotify. I'm using the passport-spotify package, which is basically the same as the twitter one we went over today so I can authenticate with it, I just can't figure out how to save that to my database.
the code I currently have is:
![screen shot 2015-08-25 at 6 26 27 pm](https://cloud.githubusercontent.com/assets/7719096/9481287/dff0cef0-4b56-11e5-8b80-1395a07304ce.png)
previously I was trying to use Sequelize's .findOrCreate() method, which was much shorter but still didn't work:
![screen shot 2015-08-25 at 6 27 13 pm](https://cloud.githubusercontent.com/assets/7719096/9481298/fbf742d2-4b56-11e5-9fbe-d347c77f7675.png)

The error I'm getting in my browser is (and previously was getting same error for .findOrCreate):
![screen shot 2015-08-25 at 6 27 57 pm](https://cloud.githubusercontent.com/assets/7719096/9481309/12b8e2e6-4b57-11e5-9c6c-52b12246250b.png)

I've connected my database using `var db = require("./db/connection");` but I'm not sure what to do from here since I've followed the Sequelize docs word for word. Asked classmates and the TAs, too, but still getting the error.

**Comment by RobertAKARobin** [comment]
What does your `connection.js` look like?

**Comment by msteffan** [comment]
Here's a screenshot of connection.js:
![screen shot 2015-08-25 at 6 32 03 pm](https://cloud.githubusercontent.com/assets/7719096/9481360/a6de46dc-4b57-11e5-9d11-f7d29254742d.png)

**Comment by RobertAKARobin** [comment]
Try `db.models.User.findOne` instead of `db.User.findOne`.

**Comment by msteffan** [comment]
Well, that doesn't _not_ work because it solved one error (it's adding a user to the database—hooray!) but it now thinks for a reallllllly long time and returns this error:
![screen shot 2015-08-25 at 6 39 42 pm](https://cloud.githubusercontent.com/assets/7719096/9481501/efe0163e-4b58-11e5-8e33-9b9d17660c84.png)

**Comment by RobertAKARobin** [comment]
Looks like a Passport error! Unfortunately I'm not sure what to say about that. Jesse may have a better idea when he gets in tomorrow!

**Comment by msteffan** [comment]
Ok, I'll dig into the Passport docs more tonight to keep debugging;
otherwise I'll check-in about this in the morning. Thanks, Robin!

On Tue, Aug 25, 2015 at 6:44 PM, Robert Thomas notifications@github.com
wrote:

> Looks like a Passport error! Unfortunately I'm not sure what to say about
> that. Jesse may have a better idea when he gets in tomorrow!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/pbj-project3/issues/25#issuecomment-134762779.

## 

_email *// msteffan2012@gmail.com
*cell *// (206) 498-7863
*twitter_ https://twitter.com/melissasteffan // _LinkedIn_
http://www.linkedin.com/pub/melissa-steffan/4b/567/9aa

**Comment by jshawl** [comment]
what does your `passport.use` function look like?

**Comment by jshawl** [comment]
also try stopping and restarting? keeping an eye on this issue - sounds like a fun one to help out with!

**Comment by jshawl** [comment]
also reaaallllyyy long time usually indicates you're not invoking a callback somewhere. I suspect it's in the `passport.use` function

**Comment by msteffan** [comment]
passport.use looks like:
![screen shot 2015-08-26 at 9 48 38 am](https://cloud.githubusercontent.com/assets/7719096/9495085/bacafb1a-4bd7-11e5-97a8-ea9bc13f0fe6.png)

Current error I'm getting is: 
![screen shot 2015-08-26 at 9 50 30 am](https://cloud.githubusercontent.com/assets/7719096/9495128/f80d6d64-4bd7-11e5-8744-da36ed35fb4f.png)

If I remove the "profile" line, then it throws the authorization token error that I documented earlier.
It's not redirecting to spotify, and our logout function doesn't work either. I've been working on this for 2 hrs at least, so I'd love to grab 20 minutes of help if you're available, Jesse.

**Comment by jshawl** [comment]
:+1: comin over!
