### ISSUE TITLE
Simple (?) css class-change failing

### ISSUE THREAD

**Issue by tomBeach** [ga-dc/pbj-project3#27]
I am updating our rollover menu with class changes to identify the current "view".  Each menui dive has a class of "menuLink" but the current view has an additional class of "thisPage".  The js correctly removes "thisPage" from the previous div and adds it to the new div (verified by inspect element) but the div newly adorned with "thisPage" remains in its untouched state on-screen (plain ol' white).  

The update function is below: whichMenuItem is the "new" current view (a jquery object previously identified); self is the DisplayObject (which stores various display states as a view controller); self.menuArray is a list of all menu elements as jquery objects stored on DisplayObject.  Any thoughts?  Thanks!

``` js
        function updateMenu(whichMenuItem, self) {
            console.log("updateMenu");
            console.log('  self.name: ' + self.name);
            for (i = 0; i < self.menuArray.length; i++) {
                nextMenuItem = self.menuArray[i];
                console.log("  nextMenuItem: " + nextMenuItem.attr('class'));
                nextMenuItem.removeClass("thisPage");
            }
            whichMenuItem.addClass("thisPage");
         }
```

**Comment by RobertAKARobin** [comment]
So when you inspect the element, _you can see that the class has changed_, but it isn't looking any different for some reason?

When you inspect the element, can you see the styles you're looking for on the right-hand side of the page? You should see `.thisPage` over there.
![screen shot 2015-08-26 at 9 54 03 am](https://cloud.githubusercontent.com/assets/6268177/9495222/6bcf9286-4bd8-11e5-8702-bd8b7f9e3088.png)
