### ISSUE TITLE
Deployment Error 

### ISSUE THREAD

**Issue by edwardpark** [ga-dc/pbj-project3#30]
trying to deploy app to heroku today, getting this error: 
Error: Cannot find module './config/keys.json' 2015-08-26T07:21:42.042478+00:00 app[web.1]: throw err; 2015-08-26T07:21:42.042484+00:00 app[web.1]: at Function.Module._resolveFilename (module.js:336:15)

We put our API keys in a keys.json file and placed that in the gitignore... wondering how we go about deployment now.

**Comment by edwardpark** [comment]
sorry just want to make sure someone sees this, previous has been open about a hour now.

**Comment by RobertAKARobin** [comment]
Hey, Ed, looking now
