### ISSUE TITLE
Could we use one of our 20 minute tokens on an OOJS question?

### ISSUE THREAD

**Issue by jeffjones89** [ga-dc/pbj-project3#32]
We have one global variable we're not sure where/how to store that we'd like to hide behind an object.

More broadly, we're passing an array of items to another object view/constructor and we think the group would benefit from talking through this with an instructor just to cement the process.

Let me know if you'd like more specific questions...our code currently works as is so not a major trouble shooting issue but more of a next steps kind of thing.

**Comment by RobertAKARobin** [comment]
Can we try to do it remotely? We're a little short-staffed at the moment! If you push your code to Github and point out what you're talking about, I'd be happy to take a look!

**Comment by jeffjones89** [comment]
Sure! https://github.com/jeffjones89/MenuBuilder 

You'll notice in the itemView.js folder a global "meal" array. We're basically capturing individual food items the user wants to add to their meal to calculate the total nutritional value of the meal itself. We had some trouble trying to figure out where to hide that array, because theoretically (I think!) we'd want that array to persist through as a promise or have a "mealView.js" file to capture the return value of the function so that we could format the meal view.

It works as is, but it was just bugging us. Perhaps we could talk through the second part when you guys are back up and running full strength if we haven't worked out the kinks of passing an array objects between views.

**Comment by RobertAKARobin** [comment]
You could have `meals` be a property of the Item model, and then push to that:

```
  addToMeal: function(item){
    this.item.meal.push(item);
  }
```

Kinda confused by the naming of things, particularly that there seem to be different kinds of `item`, and that `meal` refers to an array... Shouldn't it be `meals`?

**Comment by jeffjones89** [comment]
Yeah I think we might refactor from Items to Menu, and then pass items between the Menu and the Meal.

**Comment by RobertAKARobin** [comment]
We good to go here, then?

**Comment by jeffjones89** [comment]
I think on the initial array issue that makes sense. Can I just resubmit an issue or message the instructors if the group feels they'd benefit from talking through the other areas (passing the array to ohter views, etc) later this afternoon?

**Comment by RobertAKARobin** [comment]
Totes McGoats!
