### ISSUE TITLE
where to put extra javascript code?

### ISSUE THREAD

**Issue by ghost** [ga-dc/pbj-project3#33]
I'm trying to include a search bar in my app. I have the search form in views/index.hbs, but I don't know which file to put event listeners and other js code for the search bar in.

**Comment by RobertAKARobin** [comment]
Ack, sorry, Yvonne! I got caught up in figuring out another issue. Looking now!

**Comment by RobertAKARobin** [comment]
Phew. OK. Can you push your code to Github?

**Comment by ghost** [comment]
I just pushed the code but I figured it out! It works when I put it in my assets/application.js file.  However, I have another issue. When I push the enter button, my code says to have an alert pop up. The issue is that it's rendering it twice. How do I make it just pop up once?

**Comment by jshawl** [comment]
Can you share your code please?

**Comment by ghost** [comment]
Ops! sorry! 
I just updated my code, so I have the search embeded in views/layout.hbs

```
      <form class="search">
        <input type="search" placeholder="Search..." name="search">
        <input type="submit" style="visibility: hidden;" value="Submit">
      </form>
```

and then I put the alert in app/assets/application.js

```
 // 13 = enter key
$(".search").keypress(function(event){
  if(event.which == 13)
    alert("enter pressed");
});

```

It can be found here: https://github.com/YvonneWang/group10-project3

**Comment by jshawl** [comment]
what if you try keyup instead of keypress? http://stackoverflow.com/questions/3396754/onkeypress-vs-onkeyup-and-onkeydown

**Comment by ghost** [comment]
I tried these two codes, but it's not working. The alert box for both codes doesn't show up. I then replaced keyup with keydown and I get the same result as keypress.

```
$(".search").keyup(function(event){
  if(event.keyCode == 13){
    alert("enter pressed")
  };
});

$(".search").on("keyup", function(event){
  if(event.keyCode == 13){
    alert("enter pressed")
  }
});
```

**Comment by RobertAKARobin** [comment]
The page refreshes every time you press enter. That's because you put a "submit" button after it, and you put it inside a form. By default, those submit when you hit "enter". You only need `<form>` if you're actually making a form; one button usually doesn't need to be inside a `<form>`.

I fixed it by replacing the form with this:

```
      <div>
        <input class="search" type="search" placeholder="Search..." name="search">
      </div>
```

That screws up the CSS, but that's easy to fix.

**Comment by RobertAKARobin** [comment]
Also, your `layout.hbs` should be the only file that has `<!DOCTYPE html>` and the `<head>` and all that stuff. `index.hbs` is put _inside_ `layout.hbs` thanks to the `{{{body}}}` in `layout.hbs`. If you look at the source code of your webpage in your browser, you'll see what I mean.

**Comment by RobertAKARobin** [comment]
It's been a while since this was updated, so I'm going to close it. Feel free to open a new issue linking to this one!
