### ISSUE TITLE
Sass Issues

### ISSUE THREAD

**Issue by silviascript** [ga-dc/pbj-project3#34]
Hello, 

I'm having an issue with my css and sass. I installed Node-Sass and Node-Sass-Middleware to use Sass and minimize into css. When I save my scss file and refresh the page, I receive the new styling I have added. However, when I refresh the page without saving new additional styling, the page loads only the html content, no css. I receive an error of "http://localhost:3000/styles.css Failed to load resource: the server responded with a status of 404 (Not Found)".

It's odd because I am not receiving any errors in Terminal.

```
source: /Users/Siltastic/Sites/farmony-markets/public/sass/styles.scss
dest: /Users/Siltastic/Sites/farmony-markets/public/css/styles.css
read: /Users/Siltastic/Sites/farmony-markets/public/css/styles.css
render: /Users/Siltastic/Sites/farmony-markets/public/sass/styles.scss
```

When I refresh the page, I receive this in Terminal. I know it's not rendering anything because I didn't add any additional styling, but I assume I would still see my previous styling. **My main concern is that this may not work in Heroku when we deploy.**

```
source: /Users/Siltastic/Sites/farmony-markets/public/sass/styles.scss
dest: /Users/Siltastic/Sites/farmony-markets/public/css/styles.css
```

``` javascript
// Require express to application.
// Connect Sass to application.
// Connect express to application.
// Connect path middleware.
var express = require("express");
var sassMiddleware = require("node-sass-middleware");
var app = express();
var path = require("path");

// Connect bodyparser middleware.
var bodyParser = require("body-parser");
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

// Connecting to public assets.
app.use(sassMiddleware({

  // This is the Sass source.
  src: __dirname  + '/public/sass/',

  // I'm joining the Sass source with the CSS in order to minimize it.

  dest: path.join(__dirname, '/public/css/'),
  debug: true,
  outputStyle: 'compressed',
  prefix: '/prefix'
}));

app.use("/public", express.static(path.join(__dirname + "/public")));

// Set up the HBS.
app.set("view engine", "hbs");
```

Tree of my public directory.

```
├── planning
│   ├── user-experience
│   │   ├── README.md
│   │   └── img
│   │       ├── 20150823_0000_FM_2015_Planning-Sketches.jpg
│   │       ├── 20150823_0000_FM_2015_Web-1.0_Home_Introduction.jpg
│   │       └── 20150823_0001_FM_2015_Web-1.1_Home_SearchMarkets.jpg
│   └── user-interface
│       ├── README.md
│       └── img
├── public
│   ├── css
│   │   └── styles.css
│   ├── img
│   ├── js
│   │   ├── jquery.js
│   │   ├── market_api.js
│   │   └── script.js
│   └── sass
│       └── styles.scss
└── views
```

**Comment by silviascript** [comment]
Also, is my naming convention for my public directories alright? I've been seeing directories called styling, javascripts, and images. I wonder if I should have my css and scss in the same directory too. Any suggestions?

**Comment by jshawl** [comment]
Whatever is linking to `http://localhost:3000/styles.css` - can you add `/css/styles.css`?

And yes! your structure looks right!

**Comment by jshawl** [comment]
Also, I've struggled with node sass middleware before. Maybe you can compile by hand using sass gem, and link to the compiled stylesheet

**Comment by silviascript** [comment]
@jshawl It doesn't work with `/css/styles.css` when I add it into the layout.hbs flle. Sass gem? Are you talking about this one? https://github.com/sass/sass. Would I need to install the gem in my project directory?

**Comment by jshawl** [comment]
nope you can do this via the command line check out the command line example under usage here - http://sass-lang.com/documentation/

**Comment by silviascript** [comment]
I installed the gem and it seems to be working in terminal, but how would I see it on on my local host? I created a map and tried to link it to the layout.hbs, but I'm having no luck.

**Comment by mattscilipoti** [comment]
I'm just saying what Jesse said, but in a slightly different way.  There are ways to automatically compile your styles.scss file to your styles.css file.  Setting up the automatic processing is difficult.  Instead, we recommend you use the sass gem, manually, to compile "sass/styles.scss" and save the results to "css/styles.css".   Your app will not know about "sass/styles.scss". You will just use "css/styles.css" the same way you reference any css file.

**Comment by RobertAKARobin** [comment]
I'm going to close this since it's been a little while. Feel free to open a new issue linking to this one!
