### ISSUE TITLE
No Default Engine was Specified Error

### ISSUE THREAD

**Issue by malissaromero** [ga-dc/pbj-project3#36]
We are getting this error and our research has said the view engine needs to be set and we already have that. We also compared our code with a code that is working and do not see a difference. 

![screen shot 2015-08-26 at 2 11 52 pm](https://cloud.githubusercontent.com/assets/11203264/9501960/6d41fb58-4bfc-11e5-996a-5901138e3d1c.png)

Here is my code: https://github.com/malissaromero/wanderlist

**Comment by jshawl** [comment]
This line looks right - https://github.com/malissaromero/wanderlist/blob/44723eca4ffce34f27bb2004c1cdf17bd650ec98/app.js#L10

did you try stopping and restarting the server?

**Comment by malissaromero** [comment]
Lon solved it by commenting out this line because it was a duplicate. 

`var app = express();`
