### ISSUE TITLE
Click events for appended elements

### ISSUE THREAD

**Issue by Curtismn87** [ga-dc/pbj-project3#37]
When you click a link in our nav we want to append inputs for the user to enter information into the database.

``` js
$("#main_nav li:eq(5)").on("click", function(){
    console.log("profile button clicked");
    var container = $(".contents");
    container.empty();
    container.append("<button type='submit' id='submitStock' value='submit'>Submit</button>");
  });

$(document).on("click", "#submitStock", function(){
  console.log("submit button!!");
});
```

This does exactly what we want it says it will do. It appends a submit button into the DOM and when you click the button the console.log appears.

The question we have is why do we have to use $(document) as the selector? $("#submitStock") or anything else we tried doesn't work.

**Comment by jshawl** [comment]
because when the page loads, the `#submitStock` element doesn't exist yet, so you can't add an event listener to it. Check out http://stackoverflow.com/a/18144022/850825

**Comment by RobertAKARobin** [comment]
I'm going to close this. Feel free to open a new issue linking to this one!
