### ISSUE TITLE
Can't access queried Object

### ISSUE THREAD

**Issue by omarimayerswalker** [ga-dc/pbj-project3#39]
When I `console.log(vendor)` it returns the object as expected but if I `console.log(vendor.id)` I get undefined. 

```
var Vendor = require("../db/connection").models.Vendor;
var Market = require("../db/connection").models.Market;

module.exports = {
    marketSearch: function(req, res){
        var userSub = req // this is working
        console.log(userSub + " " + Vendor) // this returns Soupergirl + [object SequelizeModel:vendor]
        Vendor.findAll({ where: {name: userSub }}).then(function(vendor){
            console.log(vendor.id)
        })
    }
}
```

`console.log(vendor)` returns:

![selection_002](https://cloud.githubusercontent.com/assets/10659084/9503212/9ae00a12-4c03-11e5-936f-0e4eb653f044.png)

**Comment by RobertAKARobin** [comment]
It's because `findAll` returns an array of records, even if that array contains one thing. If you just want the ID of the first one, you'd need `vendor[0].id`. Make sure your variables names make sense!
