### ISSUE TITLE
using .update and .create to communicate with the database on newly created elements

### ISSUE THREAD

**Issue by pdavies88** [ga-dc/pbj-project3#40]
we are able to use self.list.update(data) to update a list in our database. However when trying to update content i keep getting Uncaught TypeError: Cannot read property 'update' of undefined this is the same as when I try to do .create Uncaught TypeError: Cannot read property 'create' of undefined trying to figure out why .update and .create work for our lists but not for our content sections. List have many Contents, also tried List.contents and still have the same error.

thx for the assistance

**Comment by RobertAKARobin** [comment]
Can you show the context of this code? I'd like to see what all's around it.

**Comment by pdavies88** [comment]
```
$("#editContent").on("click", function() {
      var self = this;
      var contents = $(this).closest(".contents")
      var form = $("<form>Edit Contents</form>")
      var submit = $("<button>Edit Content</button>")
      var activity = $("<input placeholder='activity'>")
      var location = $("<input placeholder='location'>")
      var goal_date = $("<input placeholder='goal_date'>")
      form.append(activity)
      form.append(location)
      form.append(goal_date)
      form.append(submit)
      contents.append(form)
      submit.on("click", function(event){
        event.preventDefault();
        console.log("cool button bro")
        var c = new Content({
          activity: activity.val(),
          location: location.val(),
          goal_date: goal_date.val()
        })
        console.log(c)
        self.contents.update(c)
        // updateList: function() {
        //   var self = this;
        //   var data = {  author: $('input[name=author]').val(),
        //                 name:   $('input[name=name]').val()
        //                };
        //   self.list.update(data)
        //   .then(function() { self.render();
        //   });
        // }
        var view = new ContentView(c)
        $(".activity").html(view.activity())
        $(".location").html(view.location());
        $(".goal_date").html(view.goal_date());
        form.remove()
      }.bind(this))
      console.log("edit content button")
    });
```

**Comment by RobertAKARobin** [comment]
Try putting a `console.dir(self)` (better than `console.log(self)`) right above it. What does it give you? Is it what you expected?

**Comment by pdavies88** [comment]
its giving me button#editContent but what i'd like it to give me is var c and the data inside of it

**Comment by RobertAKARobin** [comment]
I think you're looking at the `console.log(c)` you have in there. You can always take my fancy approach of putting `console.log("FOOOOOOOO")` right before the thing you want so make it more obvious.

**Comment by pdavies88** [comment]
that makes sense but I know the var c has the data that I want to be put into the DB im just unsure how to call on that to create new content in the DB with the vals that are input in var c

**Comment by RobertAKARobin** [comment]
The problem here is that you're trying to call `self.contents.update`. That gives you `Cannot read property 'update' of undefined`. That means your `self.contents` is undefined. `c` isn't important here; you need to figure out what's going on with `self` and `self.contents`.

**Comment by pdavies88** [comment]
We git it sorted. Thanks!
