### ISSUE TITLE
Another Sass Issue

### ISSUE THREAD

**Issue by silviascript** [ga-dc/pbj-project3#42]
Related to this issue, https://github.com/ga-dc/pbj-project3/issues/34.

I'm not having an issue connecting my sass to our Express app anymore. I have installed the sass gem successfully with help from Matt and Jesse. In terminal, I am watching my scss file and sending the output to my css file. Unfortunately, it's not updating the compiled version for css. I've researched and solved two of my issues, but I can only update the css file if I manually add a new style, which defeats the purpose of watching the scss file, right?

**Comment by silviascript** [comment]
Solved it.

**Comment by mattscilipoti** [comment]
`sass --watch` watches the input (sass/style.scss) file.  When you change something in the input file  (.scss), it compiles the sass in to your output file (css/style.css).  Is that not working?
