### ISSUE TITLE
issue #33 continued, alert popping up twice when hitting enter

### ISSUE THREAD

**Issue by ghost** [ga-dc/pbj-project3#43]
https://github.com/ga-dc/pbj-project3/issues/33

I tried two things but also got the same result as before, alert popping up twice in a row.
1. got rid of the submit button in the form for search
2. got rid of the entire form tag for the search and replaced it by what you wrote above. I still got the same result, alert popping up twice in a row.

**Comment by RobertAKARobin** [comment]
See my last comment in the other issue. It's because you have two `<head>`, because you put `<!DOCTYPE html><html><head>` etc. in both your `index.hbs` and `layout.hbs`. Both of those `<head>` link to your `application.js` script, so it's running twice.

**Comment by ghost** [comment]
OH Got it! :+1: Thank you! That also kinda solved another issue we were having.
