### ISSUE TITLE
Issue updating Deployment to Heroku

### ISSUE THREAD

**Issue by edwardpark** [ga-dc/pbj-project3#45]
![screen shot 2015-08-27 at 9 08 52 am](https://cloud.githubusercontent.com/assets/7883907/9521390/9ecd0bc2-4c9c-11e5-82b0-b3e763512c2b.png)

kinda confused this has been working previously but now it just stopped even though my pull branch is technically been update from the remote master branch.

**Comment by RobertAKARobin** [comment]
When in doubt, try `git diff heroku/master` and see what's different!

**Comment by edwardpark** [comment]
ok trying to go through this and I can s..

wait we have have pull heroku master ?! ugh how did I miss that. ok thanks!
