### ISSUE TITLE
Heroku database issues

### ISSUE THREAD

**Issue by rewarren** [ga-dc/pbj-project3#47]
error when trying to connect to our local db

<img width="919" alt="screen shot 2015-08-27 at 10 23 10 am" src="https://cloud.githubusercontent.com/assets/10967783/9522986/ba68ba94-4ca5-11e5-9c62-0377e0ef43ea.png">

**Comment by RobertAKARobin** [comment]
Is the blue elephant running? If so, do you have `psql` or another Node app running elsewhere?

**Comment by rewarren** [comment]
it wasn't, so we ran the blue elephant.  it returned a long list of pg-dump and pg-restore messages but we're still unable to connect

**Comment by RobertAKARobin** [comment]
...huh. I'll come look.
