### ISSUE TITLE
Add Font Files to Express

### ISSUE THREAD

**Issue by kristingreenslit** [ga-dc/pbj-project3#48]
We have a web font file that we'd like to use in our project. We've researched how to reference a .ttf file in express and node, but haven't been successful in getting it to work properly. It would be great to learn how to do this vs. using the google cdn or typekit. Thanks!

We're in classroom 1.

**Comment by RobertAKARobin** [comment]
Oh, man. Fonts are a pain in the butt -- much more so than other assets like images. Can I ask that you just use the CDN?

**Comment by kristingreenslit** [comment]
Robin: we certainly can, but if given the opportunity to learn how to work with a font file we'd like to.

**Comment by jshawl** [comment]
first i would make sure you can visit the font via URL.

e.g. put font in `public/fonts/myfont.ttf`

Then try to access in browser:

`http://localhost:3000/fonts/myfont.ttf`

Then once that is working, you can reference the font with `@font-face`: https://css-tricks.com/snippets/css/using-font-face/

**Comment by RobertAKARobin** [comment]
...but make sure you timebox yourselves on this. If you find yourselves spending more than half an hour, let alone a whole hour, working on the fonts alone, drop it and do something else. I'm having flashbacks to Melissa spending like 2 days trying to get fonts to work during the last project.

**Comment by kristingreenslit** [comment]
Robin: understood! 

Jesse: This is what I'm getting right now, no route but when I go to localhost:3000/public/fonts/transat_text.ttf in my browser, the word "public" is dropped from the url and the font file downloads.

<img width="492" alt="screen shot 2015-08-27 at 11 07 18" src="https://cloud.githubusercontent.com/assets/5890436/9524320/537555b6-4cac-11e5-9cb6-7054462cc458.png">

**Comment by RobertAKARobin** [comment]
That actually seems to be working correctly!

**Comment by kristingreenslit** [comment]
perfect! I wasn't sure if that was intended behavior or that I made a mistake, so thanks for confirming that I was on the right track. Trying now to implement @font-face.

**Comment by kristingreenslit** [comment]
unfortunately I can't get this to work at the moment so I'll have to move on. Here's my code and I also tried this solution, but no dice: https://www.npmjs.com/package/connect-fonts

<img width="732" alt="screen shot 2015-08-27 at 11 41 04" src="https://cloud.githubusercontent.com/assets/5890436/9525147/b27aabde-4cb0-11e5-95dc-cd253efc6b50.png">

**Comment by RobertAKARobin** [comment]
Instead of `url('transat_text.ttf')` try `url(/public/fonts/transat_text.ttf)` -- the same thing you typed into your address bar.

**Comment by kristingreenslit** [comment]
Robin: thanks for the suggestion. Couldn't get that to work, also tried the following but that didn't work either.

<img width="749" alt="screen shot 2015-08-27 at 11 56 54" src="https://cloud.githubusercontent.com/assets/5890436/9525608/e66aca4e-4cb2-11e5-9b9c-c8b0717c4cdc.png">

**Comment by RobertAKARobin** [comment]
I'm going to say that you should try without for now, then. Sorry about that!

**Comment by kristingreenslit** [comment]
Robin: no worries, and thanks!
