### ISSUE TITLE
heroku sequelize lack of cooperation

### ISSUE THREAD

**Issue by adrianshep** [ga-dc/pbj-project3#50]
We've removed Twitter Auth to test whether Heroku deployment will work without it and are now seeing this error:

Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED

which we're interpreting as Heroku not speaking to our db. We're trying to read documentation on this and not getting anywhere.

**Comment by RobertAKARobin** [comment]
Can you push your code to Github so I can try it on my computer? I hate this error.

**Comment by adrianshep** [comment]
Okay, thank you, we're pushed now in Github.  

https://github.com/iamjustinprice/speakapp

**Comment by RobertAKARobin** [comment]
Where's your seed data?

**Comment by adrianshep** [comment]
We don't have a seed file yet; is that a make or break thing? We can create some now if it is.

**Comment by RobertAKARobin** [comment]
Nope, just thought I remembered you having one. Hang tight.

**Comment by ebirving** [comment]
When I run heroku pg:psql, it's only showing the test table we created in the db. So, I think the stumbling block may be running a migration. How do we make heroku run our migrate.js file during deployment and/or make sure that the DATABASE_URL points to the database we've set up?

**Comment by RobertAKARobin** [comment]
Got it. First, run this:

```
heroku addons:create heroku-postgresql:hobby-dev
```

Then, update your connection.js with this:

https://github.com/ga-dc/tunr_node_oojs/blob/275f327c313ee30848bad007605c04e86e1cb835/db/connection.js#L3-L13

Then, run `heroku run node config/migrate.js`

Then you should be in business.

**Comment by RobertAKARobin** [comment]
I take it by your silence that this worked! If not, open a new issue linking to this one.

**Comment by adrianshep** [comment]
This works a charm and... the Twitter Authentication works with it now, too! So THANK YOU!
