### ISSUE TITLE
How to access session data throughout app?

### ISSUE THREAD

**Issue by alexbannon** [ga-dc/pbj-project3#51]
So we have sessions being created, at least req.session exists and the index.js can access it.

To update, our app has users who have pins, and I want to only access one users pins, and which user is defined by the session, so I'm trying to access that session in both the backend and frontend.

I thought I could just do var Session = req.session
module.exports = Session
and then require index.js elsewhere, but I'm running into issues.

I expected sessions to be much closer to rails, in that it's the everpresent variable.

What do I do to access the session of a user?

**Comment by alexbannon** [comment]
to clarify, trying var Session = require("../../../index")
gave me the error "Uncaught ReferenceError: require is not defined" when used in the frontend pin.js model.

**Comment by RobertAKARobin** [comment]
`require` is exclusively back-end Javascript; you can't require something on the front-end. The best you can do is to use a `<script>` tag or make a GET request to the file with AJAX.

However, if you want to pass data from the sessions to the front-end, you could do something like this:

``` js
app.get("/", function(req, res){
  res.send("myview", {session: req.session});
});
```

Now, if you're using Handlebars, you'll be able to do something with `{{session}}`.

Alternatively, you could make a GET "/user" route that returns a JSON string with the current user's data:

``` js
app.get("/user", function(req, res){
  res.json(req.session);
});
```

Then, you can access that data with AJAX.

**Comment by RobertAKARobin** [comment]
I'm going to close this. Feel free to open a new one linking to this if need be!
