### ISSUE TITLE
Trouble with html

### ISSUE THREAD

**Issue by walter-0** [ga-dc/pbj-project3#53]
We are trying to put the front end js and css together but we are having naming issues. Below is the html for our index view (still a single page app)

![screen shot 2015-08-27 at 1 11 36 pm](https://cloud.githubusercontent.com/assets/10503240/9527500/a9a18a3e-4cbd-11e5-90b5-5a30864d65a2.png)

And here is the corresponding questionView.js

![screen shot 2015-08-27 at 1 12 27 pm](https://cloud.githubusercontent.com/assets/10503240/9527729/bd8b309e-4cbe-11e5-933a-44f998007140.png)

What happens now is all the entries are being placed in one entry div.
![screen shot 2015-08-27 at 1 13 08 pm](https://cloud.githubusercontent.com/assets/10503240/9527881/a0a320d0-4cbf-11e5-9a85-44b3fcc91ece.png)

And each of these is being given an id
![screen shot 2015-08-27 at 1 13 39 pm](https://cloud.githubusercontent.com/assets/10503240/9527890/b11f4f74-4cbf-11e5-9f71-451398cf7db0.png)

What should happen is each question ( 1, 2, 3) should have their own entry div, and the title of each question should go into its entry-title.

**Comment by RobertAKARobin** [comment]
Fix your indenting with the divs! It looks like you have a div that you forgot to close, but I can't tell. If you're not sure either, run it through the HTML validator:

http://validator.w3.org

**Comment by walter-0** [comment]
Good catch. Fixed that div.

![screen shot 2015-08-27 at 1 43 07 pm](https://cloud.githubusercontent.com/assets/10503240/9528252/a05d1b42-4cc1-11e5-868f-6384467ffdad.png)

**Comment by walter-0** [comment]
Overindented, oops

![screen shot 2015-08-27 at 1 52 43 pm](https://cloud.githubusercontent.com/assets/10503240/9528550/0eefeb4c-4cc3-11e5-8686-4b19463e8226.png)

**Comment by RobertAKARobin** [comment]
Is  there any difference? Did you actually validate your HTML?

**Comment by walter-0** [comment]
No. The HTML is valid. Our issue is partially with renaming things in the JS but we're confused about how to organize the DOM elements so that we can see what we want.

**Comment by RobertAKARobin** [comment]
This stands out to me:

```
$('#qtitle' + this.question.id).append...
```

Isn't `qtitle` a variable? You have it inside a string.

**Comment by walter-0** [comment]
Yes, but I think it should either be renamed to entry or entry-container. Our naming is not integrated.

**Comment by RobertAKARobin** [comment]
I think the problem here is you're selecting `$(".question-title")`. There are multiple `question-title`s on the page. So when you do `$(".question-title").append`, jQuery isn't sure which one you want to append to, so it just picks the first once, hence why all your questions are going to the same place. You need to specify which `question-title` you want.

**Comment by RobertAKARobin** [comment]
I'm going to close this. Feel free to open a new one linking to this if need be!

**Comment by walter-0** [comment]
Okay, thanks for trying.

**Comment by RobertAKARobin** [comment]
Did my last comment not work? I didn't hear back from you!

**Comment by walter-0** [comment]
It sort of worked. We decided to start over with the view we were working on. Matt's here now so hopefully we can solve it soon.

**Comment by RobertAKARobin** [comment]
Okay!
