### ISSUE TITLE
Git Revert Help

### ISSUE THREAD

**Issue by jeffjones89** [ga-dc/pbj-project3#57]
Had a merge issue (the master merged into Cheik's remote branch instead of the other way around) and we're trying to revert.

Able to locally, but not push because my branch is behind the master branch. 

https://github.com/jeffjones89/MenuBuilder/commits/master

We'd like to revert to my commit of "saving meals to database" b503 etc.

**Comment by RobertAKARobin** [comment]
OK, I'll come in person.

**Comment by jeffjones89** [comment]
Thanks we're in classroom 1.
