### ISSUE TITLE
heroku not connected to database 

### ISSUE THREAD

**Issue by chrislovett03** [ga-dc/pbj-project3#62]

**Comment by amaseda** [comment]
Hey Christine,

What exact error are you getting?

Walking through this might help. https://devcenter.heroku.com/articles/getting-started-with-nodejs#provision-a-database

**Comment by jshawl** [comment]
I also recommend pasting the output of `heroku logs`

**Comment by RobertAKARobin** [comment]
It's been a while, so I'm going to close this. Please feel free to open a new issue linking to this one!

**Comment by chrislovett03** [comment]
Thanks, Adrian. We are having trouble connecting our database to heroku. We
abandoned the issue for a while and are going to try again this morning.
Matt was helping us  for a little while last night but we couldn't figure
it out.

**Comment by RobertAKARobin** [comment]
Can you create a new issue, Christine?
