### ISSUE TITLE
CSS Help

### ISSUE THREAD

**Issue by silviascript** [ga-dc/pbj-project3#63]
Evening, I've been trying to add an image in this pink container and I want the image to scale down to fit inside the square. I had it working earlier but when I started working in media queries, I think something over rode it. I tried removing styles and I learned it's my 100% height that is making it disappear. It's odd, because the way I set it up should fit in the shape.

It's there, but the scaling is off.
![screen shot 2015-08-27 at 7 31 35 pm](https://cloud.githubusercontent.com/assets/10377524/9535784/39462804-4cf3-11e5-97f3-780b567b32f7.png)

It's gone.
![screen shot 2015-08-27 at 7 31 53 pm](https://cloud.githubusercontent.com/assets/10377524/9535787/3f170d52-4cf3-11e5-9eb9-1f963180b780.png)

Not sure what I'm doing wrong.

**Comment by jshawl** [comment]
what css are you using to position / size the image?

**Comment by silviascript** [comment]
Ooops, meant to paste the code. https://github.com/siltastic/farmony-markets/blob/master/assets/sass/style.scss#L302-L333. I have the image within a div and setting the div to certain size. Here is this HTML, https://github.com/siltastic/farmony-markets/blob/master/views/markets/index.hbs#L1-L12.

**Comment by jshawl** [comment]
If you give the image a red border - https://github.com/siltastic/farmony-markets/blob/master/assets/sass/style.scss#L330-L332 can you see it?

**Comment by silviascript** [comment]
Yes, only if the height is turned off.

**Comment by silviascript** [comment]
![screen shot 2015-08-27 at 7 47 59 pm](https://cloud.githubusercontent.com/assets/10377524/9535931/8cf3069c-4cf4-11e5-8844-1af06c693f60.png)

**Comment by jshawl** [comment]
I also noticed this line is pushing the image to the left - https://github.com/siltastic/farmony-markets/blob/18006b9a1589687a710dddb1512cf5a2db43fe05/assets/sass/style.scss#L323

**Comment by silviascript** [comment]
That is adding margin space to fit my grid. It's affecting the div container holding the image, not the image itself.

![screen shot 2015-08-27 at 7 50 45 pm](https://cloud.githubusercontent.com/assets/10377524/9536001/18d5e116-4cf5-11e5-89fc-bdfad7cc9b0e.png)

**Comment by jshawl** [comment]
what if you add `max-width:100%` to the `img`?

**Comment by silviascript** [comment]
That works, but I wanted the image to be proportionate when scaled to the height since all images will have different widths.

![screen shot 2015-08-27 at 7 55 38 pm](https://cloud.githubusercontent.com/assets/10377524/9536058/9f360ec0-4cf5-11e5-92a7-b3e1fbaf4bef.png)

This is my goal.
![screen shot 2015-08-27 at 7 56 09 pm](https://cloud.githubusercontent.com/assets/10377524/9536072/c4b07000-4cf5-11e5-9d55-d7a01bbac32f.png)

**Comment by jshawl** [comment]
oo what if you set the image as a background to the div? also checkout background-size: cover - https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

**Comment by silviascript** [comment]
No luck. I think I will let this go for now and retouch this in the morning. Can I meet with you in the morning?

**Comment by RobertAKARobin** [comment]
I've TOTALLY run into situations like this! My fix was to make the image a background-image, and to use `background-size:contain` to make it fit:

```
<div class="backgroundImage" style="background-image:url('{{image_url}}');"></div>
```

```
.backgroundImage{
  display:block;
  width:100%;
  height:100%;
  background-size: contain;
  background-position: center center;
  background-repeat: no-repeat;
}
```

This is one of the few situations in which I'll actually be impressed that someone used the `style=` attribute. :)

**Comment by silviascript** [comment]
Both of you, thank you so much. I had to combine both of your suggestions to create what I wanted.

**Comment by RobertAKARobin** [comment]
Woo! I'ma close this.
