### ISSUE TITLE
Getting model "not found error"

### ISSUE THREAD

**Issue by walter-0** [ga-dc/pbj-project3#68]
We have questions showing up as expected, but when we try to post answers to the question, we see this error we specified.

This is the post route for the answer controller. We are getting the error to be returned below if the question is not there.

```
router.post("/answers", function(req, res){
  Question.findById(req.params.questionId)
  .then(function(question){
    if(!question) return error(res, "not found");
    return question.createAnswer(req.body);
  })
  .then(function(answers){
    res.json(answers);
  });
});
```

I tried attaching a hidden input to the answer form, but I'm not sure how to make it get the id of the question selected.

```
<form method="post" action="/answers" class="new-answer" id="new-answer">
  <textarea name="content" form="new-answer" placeholder="Add your answer" id="new-answer-content" rows="8" cols="90"></textarea>
  <input type="submit" value="Submit" id="submit">
  <input type="hidden" name="question" value="\{{id}}">
</form>
```

Also relevant event listener for the question clicked (not best practice, pretty hacky)

```
 //event listener for each entry
  $(document).on('click','.entry',function(event){
    $(event.target).siblings().toggle();
    $(".entry-title").toggleClass("question-title")
    $(".question-content").toggle();
    $("#new-answer").toggle();
  });
```

**Comment by RobertAKARobin** [comment]
What is the error?

**Comment by walter-0** [comment]
This line is running
`if(!question) return error(res, "not found");`
How do I make the click event select the question in the database?

**Comment by RobertAKARobin** [comment]
Oh, I didn't see that.

It's not working because `req.params.questionId` expects there to be a parameter in your URL. The URL you've specified is `/answers`. If you want the URL to be able to contain the parameter, you need to add in `/answers/:questionId`. Without that, `req.params.questionId` is always going to be undefined.

**Comment by walter-0** [comment]
I changed it
![screen shot 2015-08-28 at 10 05 28 am](https://cloud.githubusercontent.com/assets/10503240/9548084/5facab34-4d6c-11e5-962d-771af5ada0b2.png)

Now I'm getting "cannot POST /answers"

**Comment by RobertAKARobin** [comment]
Oh, wait wait.

**Comment by walter-0** [comment]
https://github.com/Walter-0/group10-project3

Pushed

**Comment by RobertAKARobin** [comment]
The problem is you CAN'T post to just `/answers`. You have to post to `/answers/:questionId`. That is: `/answers/3` or `/answers/4873` or something.

**Comment by walter-0** [comment]
But it's already specified in the path. Am I missing something?

**Comment by adambray** [comment]
Your form appears to post to just `/answers`, see here:
https://github.com/Walter-0/group10-project3/blob/master/views/index.hbs#L78

**Comment by walter-0** [comment]
I changed that. Now it's just loading indefinitely.

**Comment by walter-0** [comment]
The loading stopped after a few minutes and gave me this error.

**Comment by walter-0** [comment]
Wrong screenshot

![screen shot 2015-08-28 at 10 30 19 am](https://cloud.githubusercontent.com/assets/10503240/9548678/dfac4c24-4d6f-11e5-8ae9-d7903c91c758.png)

**Comment by adambray** [comment]
Notice the URL in your address bar… it looks incorrect, maybe you still need to update where your form submits to?

**Comment by walter-0** [comment]
The paths are identical.

![screen shot 2015-08-28 at 10 42 39 am](https://cloud.githubusercontent.com/assets/10503240/9548987/9421f4e6-4d71-11e5-92f2-c233b5886a37.png)

**Comment by walter-0** [comment]
Left - index.hbs
Right app/controllers/answer.js

**Comment by adambray** [comment]
Your form needs to submit a concrete, specific questionId, i.e. /answers/28 or /answers/34 depending on the ID of the question that it’s for.

**Comment by walter-0** [comment]
Do I need the handlebars to pass in an id?

**Comment by adambray** [comment]
I believe so, yes. Note that you're already trying to pass this question id into the server on line 82, so maybe just move that up to the action part?
