### ISSUE TITLE
Heroku Database Question

### ISSUE THREAD

**Issue by jeffjones89** [ga-dc/pbj-project3#69]
Realized Sequelize/our DB isn't up and running on Heroku.

http://sequelize.readthedocs.org/en/1.7.0/articles/heroku/

Found this tutorial, but it looks like it's more geared towards creating a new app. Was just wondering if there was a way to run commands like the heroku rake db:migrate along the lines of heroku config/migrate.js from the CLI or if another alternative is better.

Thanks!

**Comment by RobertAKARobin** [comment]
Yep. Just put `heroku run` in front of a command. So `heroku run node config/migrate.js`.

**Comment by jeffjones89** [comment]
Okay cool...it's taking the command but giving me an "Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED" at the sequelize connection manager file.

Everything I've Googled is pointing me towards having to create a remote Postgres database on Heroku and define an ENV variable, then use an If statement in the index.js file to tell the application which database to connect to, local or herokus. 

Am I just overlooking some simple step? The app is deployed and all functionality works outside of our ajax call to the database, which works in a dev environment.

**Comment by jshawl** [comment]
Can you share the code that is making the db connection?

**Comment by jeffjones89** [comment]
```
var Sequelize = require("sequelize");
var db_connection = new Sequelize("postgres:///menu_db");
var Meal = db_connection.import("../models/meal");
var Item = db_connection.import("../models/item");

Item.belongsTo(Meal);
Meal.hasMany(Item);

module.exports ={
  Sequelize: Sequelize,
  db_connection: db_connection,
  models: {
    Meal: Meal,
    Item: Item
  }
};
```

AJAX Call: 

```
var url = "/meals";
    var request = $.ajax({
      url: url,
      method: "post",
      data: JSON.stringify(info),
      contentType: 'application/json'
    }).done(function(){
      $('#flash').slideDown(function() {
    setTimeout(function() {
        $('#flash').slideUp();
    }, 3000);
```

**Comment by jshawl** [comment]
This line is problematic:

``` js
var db_connection = new Sequelize("postgres:///menu_db");
```

try

``` js
var db_connection = new Sequelize(process.env.DATABASE_URL || "postgres:///menu_db");
```

**Comment by jeffjones89** [comment]
Will do...

Would I also need to add something like this into our package.json? I got the same error when trying to migrate the database remotely. 

```
"production": {
  "use_env_variable": "DATABASE_URL"
}
```

The AJAX request keeps timing out with a 503 and returning our failed AJAX console log, which makes me think we don't even have a heroku database connected on the, just the local environment.

**Comment by jshawl** [comment]
Can you use curl, postman, or cocoa rest client to single out the issue? i.e. is it a database issue or an ajax issue?

I don't think you need that in your package.json

**Comment by jeffjones89** [comment]
I think I need to run something like `heroku addons:add heroku-postgresql:dev` to actually define the first part of the conditional process.env.DATABASE_URL.

Is that completely off base? Postman returns just an application error 503, with a timeout, when I try to post to https://wdi-menubuilder.herokuapp.com/meals. The AJAX call is definitely firing to the right place. 

Fairly confident I missed a step somewhere in the deployment process to sync up the backend and migrate it initially. I'll try and retrace the heroku guide as well.

**Comment by RobertAKARobin** [comment]
Try the `addons` thing!

**Comment by jeffjones89** [comment]
Yep...good to go!
