### ISSUE TITLE
database sync failing on tunr test

### ISSUE THREAD

**Issue by tomBeach** [ga-dc/pbj-project3#7]
I tried to run the solution branch of tunr_oop as a precursor to our Project 3 express/sequelize backend and got this error: 

`24 Aug 08:32:04 - [nodemon] starting `node app.js`
Listening on port 3000
Executing (default): SELECT "id", "name", "photoUrl", "nationality", "createdAt", "updatedAt" FROM "artists" AS "artist";
Unhandled rejection SequelizeDatabaseError: relation "artists" does not exist`

Before launching I did: npm init, npm install (dependencies included express, pg, sequelize, etc in package.json), npm install -g nodemon, dropdb tunr_db, createdb tunr_db.  The app opens in the browser at first but no data is visible.  I checked psql and got "no relations found" suggesting that sync wasn't creating tables or seeding, etc.  Over the weekend I tried putting in console.log statements which showed that it called the models (artist.js, song.js) and the sync function.  (I re-cloned the code this morning and didn't touch it, other to rename the toplevel folder "B_tunr_node_oojs" (which shouldn't affect anything, right?).  Not sure what's wrong or how to go about debuging other than the console.log statements...  
One other question: other than naming the database via createdb, how does the code in tunr know what db to link to?  (I couldn't find any "db.name = tunr_db" or equivalent anywhere in the code...)
Any thoughts?

**Comment by RobertAKARobin** [comment]
Hm. Did you migrate the database first? It looks like in this case that would mean running `node db/schema.js`

**Comment by RobertAKARobin** [comment]
As for the database name, check out line 2 of `connection.js`:

https://github.com/ga-dc/tunr_node_oojs/blob/solution/db/connection.js#L2

**Comment by RobertAKARobin** [comment]
I'm going to close this, but feel free to create a new issue linking to this one!
